# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.8"]

    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.8"
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
